CREATE TABLE system__config (
	id                            TEXT NOT NULL PRIMARY KEY,
	system_email                  TEXT NOT NULL COLLATE NOCASE,
	security_email                TEXT NOT NULL COLLATE NOCASE,
	sign_up_enabled               INTEGER NOT NULL,
	sign_up_auto_activate_enabled INTEGER NOT NULL,
	totp_required                 INTEGER NOT NULL,
	totp_sms_enabled              INTEGER NOT NULL,
	magic_link_sign_in_enabled    INTEGER NOT NULL,
	google_sign_in_enabled        INTEGER NOT NULL,
	google_sign_in_client_id      TEXT NOT NULL,
	facebook_sign_in_enabled      INTEGER NOT NULL,
	facebook_sign_in_app_id       TEXT NOT NULL,
	facebook_sign_in_app_secret   TEXT NOT NULL,
	resend_api_key                TEXT NOT NULL,
	twilio_sid                    TEXT NOT NULL,
	twilio_token                  TEXT NOT NULL,
	twilio_from_tel               TEXT NOT NULL,
	created_at                    TEXT NOT NULL,
	updated_at                    TEXT
) STRICT;
