create table system__config (
	id                            integer primary key,
	system_email                  text not null collate nocase,
	security_email                text not null collate nocase,
	sign_up_enabled               integer not null,
	sign_up_auto_activate_enabled integer not null,
	totp_required                 integer not null,
	totp_sms_enabled              integer not null,
	magic_link_sign_in_enabled    integer not null,
	google_sign_in_enabled        integer not null,
	google_sign_in_client_id      text not null,
	facebook_sign_in_enabled      integer not null,
	facebook_sign_in_app_id       text not null,
	facebook_sign_in_app_secret   text not null,
	resend_api_key                text not null,
	twilio_sid                    text not null,
	twilio_token                  text not null,
	twilio_from_tel               text not null,
	created_at                    text not null,
	updated_at                    text
) strict;
